### ISSUE TITLE
Azure Subscription Access

### ISSUE THREAD

**Issue by Kdweb12** [FutureNHS/futurenhs-platform#148]
## Description of the issue:

I reached the point to "Give the Kubernetes cluster permissions to pull images from our Docker registry". It expects me having access to the azure subscription "75173371-c161-447a-9731-f042213a19da". But, I'm actually setting up the environment on my Azure Free Trial subscription. So, the images are not reachable. My question is, does the dev environment must be within the specific subscription or shared with the access? If setting up on a different subscription, the developer must create its own resource group and upload docker images, is my understanding right?

Although infrastructure/environments/dev/main.tf uses subscription "4a4be66c-9000-4906-8253-6a73f09f418d", the install_everything.sh uses production subscription
```bash
az aks update \
  -n $ENVIRONMENT \
  -g platform-$ENVIRONMENT \
  --attach-acr "/subscriptions/75173371-c161-447a-9731-f042213a19da/resourceGroups/platform-production/providers/Microsoft.ContainerRegistry/registries/fnhsproduction"
```
Do I have to get access to both subscriptions in order to run dev environment? 

Would there be a standard way to request access in the future?

**Comment by frigus02** [comment]
Hi @Kdweb12, thanks for giving this a go and reporting here. At the moment there are still a few rough edges:

- Dev environments need access to the production subscription for images. We plan to make this unnecessary by making the Docker registry public. This is a preview feature at the moment (see [docs](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-faq#how-do-i-enable-anonymous-pull-access)). But we can see if we can get that prioritized.
- Dev environments use a shared Azure Key Vault to share secrets. This is not strictly necessary but makes life a bit easier. We don't know how to make this work for external contributors, yet.
- Dev environments need an OAuth 2 client secret for authentication with Azure Active Directory B2C to do the login. Similarly, we don't know how to make this work for external contributors, yet.

There may be more, but these seem like the big ones at the moment.

We don't have those improvements on our immediate backlog. But I'll make sure to update here once that changes. At the moment the only thing you can do is probably to create your own Docker registry, manually push images to it and change the registry references locally.

**Comment by frigus02** [comment]
For reference. We're tracking the work in AB#1673.

**Comment by Kdweb12** [comment]
@frigus02 Thanks for the suggestion.

As far as I understand, currently, external contributor couldn't actually get the prototype running on either dev (own azure subscription) or local due to the authentication with AAD B2C. 

I think there should be an easier and standard way to purely run an environment at local. Of course, the local environment would not be the same as the current dev/prod. But, at least, a prototype could run for local developing. Would you consider to document or write some scripting for quicker setting up the local environment? It could be very convenient for external contributors to quickly hop on and off without setting up the entire infrastructure.

**Comment by frigus02** [comment]
I agree. The points I made above are the minimal requirements to enable external contributors to run the platform at the moment. Ideally I would like to enable developers to work fully local without the need to create any infrastructure. Creating infrastructure in the cloud seems like quite a big hurdle, especially for new contributors. 

That said, I don't know how this should work, yet. It would need a different identity provider and probably mocks for all the services that the frontend relies on.

**Comment by frigus02** [comment]
We are making steady improvements to the development process. If you're only working on the frontend, you can do that without any external setup now (no infrastructure, no AAD B2C). Run `yarn` and then `yarn dev` and you get:

- Automatic login with a static test user
- A mock API server

This means you can open the browser and go to http://localhost:3000/workspaces/directory to see the workspace directory and start browsing.

I hope we can get to a similar process for the backend microservices.

**Comment by frigus02** [comment]
Our `workspace-service`  service can now also be developed fully locally. You need Docker and the Azure CLI installed (and Rust). Then you can go to the `workspace-service` folder and run `make run-local`. This wil:

- Start a local PostgreSQL Docker container
- Start a local Azure Storage emulator Docker container
- Compile and start the application

You can then go to http://localhost:3030/graphiql and start sending queries.

If you want to use it with the frontend, you can start with frontend with `WORKSPACE_SERVICE_GRAPHQL_ENDPOINT=http://localhost:3030/graphql yarn dev` and it will connect to the local workspace service.

**Comment by frigus02** [comment]
I'm pretty sure access to Azure is not longer required to work on the project. So I'm going to close this issue. But feel free to re-open if it's not working as expected.
