### ISSUE TITLE
File upload discussion

### ISSUE THREAD

**Issue by StuartHarris** [FutureNHS/futurenhs-platform#235]
## File upload discussion

Raising this issue as a place for us to discuss how we upload files to the platform.

This is an initial suggestion of how we might do this:

![image](https://user-images.githubusercontent.com/203552/93603901-91974800-f9bc-11ea-9ec0-1a498a82c754.png)

1. The browser makes an authorised HTTPS request to get a Shared Access Signature (SAS), which is, effectively, a URL to which they can upload a temporary file. There are 3 types of SAS. (see https://docs.microsoft.com/en-us/rest/api/storageservices/authorize-requests-to-azure-storage). The documentation recommends that we use a User delegation SAS, but I think this puts a hard dependency on Azure AD (which may be fine for now, but maybe not long term). Next best is a Service SAS, which requires the service to know the Storage Account key. We can specify an upload blob (and container). We can also specify either start time, expiry time and permissions (for an ad-hoc SAS) or link it to a storage access policy on the target storage container (which could allow us to revoke all the tokens if we need to).

2. The browser uploads the file to the URI returned in step 1. We can store metadata against the uploaded file.

3. The browser calls a "publish" endpoint on the files service, which performs some checks on the uploaded file and moves it to a final destination (probably another container, potentially in another storage account). When this is complete it publishes one or more events to signify that the file is now available.

**Comment by frigus02** [comment]
That sounds great to me.

How exactly does this bind us to Azure AD? If I understand this correct "user" does not refer to end user. It sounds to me that [user delegated SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas) replaces the use of an accout key on the server side with ad AAD principal. This seems okay to be, given that we use Azure. It might actually be quite nice if we use this together with AAD Pod Identity, because it means that we use credentials, which are rotated automatically.

**Comment by StuartHarris** [comment]
Ah nice! That sounds perfect. Thanks

**Comment by frigus02** [comment]
Although it might be easier to start with using Storage Account keys because it's simpler? Upgrading to user delegated SAS seems easy enough. 🤔

**Comment by alsuren** [comment]
(we're talking about this on zoom at the moment). Looks like the shape I would expect.

Are we expecting the "files svc" to be a separate microservice, or part of the workspaces service? My instinct says it's part of the workspace service, or at the very least updates the workspace service synchronously. When you upload a file, you probably want to be able to read your own writes immediately.
