### ISSUE TITLE
[Login Page] Tabbing order for "Forgot your password" link is wrong

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#285]
[AB#2192](https://dev.azure.com/futurenhs/75407963-f812-43e5-a734-1059bbc036a3/_workitems/edit/2192)

## Description of the issue:

The "Forgot your password?" link tabbing order is wrong on the login page.  
<img width="291" alt="Screenshot 2020-09-29 at 15 28 10" src="https://user-images.githubusercontent.com/33623842/94572035-7b18a880-0268-11eb-8561-cd205f11d228.png">
Tabbing currently follows this order: Email input -> "Forgot your password?" link -> Password input)

This is because in the structure of the login component, the "Forgot your password" link appears before the Password input, but has been repositioned (using `position: relative` and `top: 50px`) to appear below the input. 

## Expected behaviour:

The tabbing should follow this order: Email input -> Password input -> "Forgot your password"

## Reproduction steps:

1. Open login page
2. Click in the Email input
3. Hit Tab
> Focus jumps from email input to "Forgot your password?" link

## Affected OS/Browsers:

MacOS 10.15.2 (Catalina) Chrome v85

**Comment by frigus02** [comment]
Yeah, this is quite unfortunate. I don't think there is much we can do here, because we don't control the HTML.

In theory we can affect the HTML with custom policies in AAD B2C or using JavaScript. Neither of those is simple, though. It's good to track this, but I assume we will have to live with it.

**Comment by frigus02** [comment]
This is super confusing, though. I wonder if we should change the CSS so the visual order matches the tab order, even if that means the forgot password link is before the password field, e.g.

![image](https://user-images.githubusercontent.com/3579251/94811972-01122c00-03ee-11eb-96c8-51f7193e189c.png)

**Comment by simplybenuk** [comment]
I don't think we can have this order. It's one of the first things a user will experience.
Every app I use I tab between the email address field and the password field to enter the app.
I can't see the Azure policies, but can you not just [change the page layout  ](https://stackoverflow.com/questions/53419368/unable-to-perform-reordering-of-sign-up-attributes-in-azure-b2c-sign-up-page)

**Comment by frigus02** [comment]
Unfortunately the reordering of fields only seems to be possible for the sign up page, not the sign in page. The sign in page has no such options.

When looking at customized emails, I saw that most of the elements on the page can be customized with custom policies. Those consist of some quite complex XML with very little documentation, though. I assume we could customize the field order with that, but I'm not 100% sure.

I just looked at using JavaScript, but there is a [guideline](https://docs.microsoft.com/en-gb/azure/active-directory-b2c/user-flow-javascript-overview#guidelines-for-using-javascript), which explicitly states that JavaScript should not be used to change the order of HTML elements on the page. However this same point says:
> Use an Azure AD B2C policy to control the order of the UI elements.

This means I can see the following low effort options:
- Move the forgot password link up as I suggested in the comment above. At least then tab order matches visual order.
- Hide the forgot password link entirely

With more effort we could:
- Investigate a AAD B2C policy.

**Comment by frigus02** [comment]
This looks like an amazing port about custom policies: https://tsmatz.wordpress.com/2020/05/12/azure-ad-b2c-ief-custom-policy-walkthrough/

I also thought about another cheeky way to change where the forgot password link lives:
1. We hide the default link in CSS with `display: none`. This also removes it from the tab order.
1. We add a new link through our custom page layout. It lives outside the `<form>`, but this might not be terrible. I bet Kim can find a way to make the link look and feel not completely out of place 🙂

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2192
