### ISSUE TITLE
[Workspace Directory] Tabbing doesn't focus on WorkspaceDirectoryItems 

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#286]
## Description of the issue:

When tabbing on the Workspace directory page the Workspace Directory Items aren't being focused, so they can't be navigated to using the keyboard. 

## Expected behaviour:

Tabbing on the Workspace directory page will focus on Workspace Directory Items.

## Reproduction steps:

1. Visit the workspace directory (/workspaces/directory)
2. Press Tab
> Workspace Directory Items aren't focused on

## Affected OS/Browsers:

MacOS 10.15.2 (Catalina) Chrome v85

**Comment by frigus02** [comment]
@declanslevin I merged #283 and now I can tab through the links on https://beta.future.nhs.uk/workspaces/directory. Can you have another look, please?

**Comment by frigus02** [comment]
Just tested in Chrome 85 on Mac and tabbing works now as described in the expected behaviour. Going to close this. Feel free to re-open if it still occurs.
