### ISSUE TITLE
NHS logo link

### ISSUE THREAD

**Issue by simplybenuk** [FutureNHS/futurenhs-platform#289]
## Description of the issue:

The NHS logo in the top right of the page currently links to nhs.co.uk, it should be [https://www.nhs.uk/](https://www.nhs.uk/)

## Screenshot(s):

If relevant please provide a screenshot of the issue.

## Expected behaviour:

Can this also open in a new tab?

## Reproduction steps:

Click on NHS logo in top right

## Affected OS/Browsers:

All

**Comment by frigus02** [comment]
Fixed in #253
