### ISSUE TITLE
[Workspace Directory] Directory item link hover/active states clash

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#325]
## Description of the issue:

When clicking (and holding) to trigger the active state on a Workspace Directory Item, if the cursor is over the anchor text, the text will be underlined which looks a little odd as the entire component is underlined as part of the active state.

## Screenshot(s):

<img width="382" alt="Screenshot 2020-10-06 at 16 01 51" src="https://user-images.githubusercontent.com/33623842/95220482-6e5afe00-07ee-11eb-9b3f-3da2c2b99c1b.png">

## Expected behaviour:

When the Workspace Directory Item is in an active state, the text shouldn't be underlined. 

## Reproduction steps:

1. Go to the /workspaces/directory
2. Click and hold on a directory item (not over the text)
> The active state for the component is triggered (yellow background / black underline), text isn't underlined
3. Click and hold on a directory item, over the text
> The active state is triggered, but the text is also underlined. 

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2253
