### ISSUE TITLE
[Create Workspace] After workspace creation has completed, browser should automatically navigate to the newly created workspace

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#327]
## Description of the issue:

After creation of a new workspace, currently you get a browser dialog stating the creation was successful. Upon acknowledging the dialog the browser doesn't navigate anywhere, it just remains on the creation page in the state it was before the "Save and complete" button was clicked. It makes it look like nothing has happened (despite the successful notification).

## Expected behaviour:

After creating a new workspace, the browser would automatically navigate to the newly created workspace.

## Reproduction steps:

1. Go to /admin/create-workspace
2. Fill in the Name and click "Save and complete"
> Dialog with 'Workspace created successfully'
3. Dismiss dialog 
> Browser remains on create-workspace page with details still listed in Name/Description field(s)

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2254
