### ISSUE TITLE
[Folder Navigation] Dropdown chevron :focus/:hover/:active states are missing

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#339]
## Description of the issue:

The folder nav dropdown chevron is missing a hover/active state. The focus state is the browser default which adds a blue outline. This doesn't match the behaviour for the rest of the site. 

## Screenshot(s):

<img width="64" alt="Screenshot 2020-10-09 at 13 08 11" src="https://user-images.githubusercontent.com/33623842/95581200-802be380-0a30-11eb-9bcb-328d1394cf66.png">

## Expected behaviour:

:hover - The background colour should be dark grey, to match the rest of the folder nav. The cursor should probably be a pointer. 
:focus/:active - There shouldn't be an outline and the background colour should be yellow.

## Reproduction steps:

1. Go to /workspaces/directory, select a workspace with folders (e.g. Selenium Testing)
2. In the nav bar on the left, hover over the dropdown chevron
> No hover state
3. Use the Tab key to focus on the dropdown chevron
> A blue outline appears
4. Click and hold on the dropdown chevron
> A blue outline appears

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2255
