### ISSUE TITLE
[Folder Navigation] Workspace name in folder nav doesn't have hover/focus/active states

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#341]
## Description of the issue:

The workspace name header in the folder nav doesn't have hover/focus/active states but it is a link to the workspace homepage. The only indication that you can click on it is that the cursor changes to a pointer. 
If using keyboard navigation, it will focus on it, but there is no indication that you are focused on the link. 

## Expected behaviour:

The workspace name should have the appropriate hover/focus/active states. 
(Focus/Active - yellow background, black bottom border
Hover - Probably the dark grey background to match the rest of the folder nav)

## Reproduction steps:

1. Go to /workspaces/directory, select a workspace
2. Use the Tab key to navigate through the page
> It will highlight the items before and after the workspace name, but not the name itself
3. Hover/click and hold on the workspace name
> No change in state

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2258
