### ISSUE TITLE
[Folder Navigation] Meatball menu "options" tooltips can interfere with clicking on items in the options menu

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#343]
## Description of the issue:

The "options" tooltip for the meatball menu buttons in the folder navigation appear on top of the options menu and can prevent you from clicking on items in the menu. 

## Screenshot(s):

<img width="409" alt="Screenshot 2020-10-09 at 13 41 01" src="https://user-images.githubusercontent.com/33623842/95584111-1530db80-0a35-11eb-9858-df22a5336abe.png">
<img width="266" alt="Screenshot 2020-10-09 at 13 41 18" src="https://user-images.githubusercontent.com/33623842/95584132-1e21ad00-0a35-11eb-98d3-90438b2190f6.png">

![meatball_options_menu_interference](https://user-images.githubusercontent.com/33623842/95584440-a86a1100-0a35-11eb-8cc5-f3b4c78d7b63.gif)

## Expected behaviour:

The options tooltip should probably no longer appear after the menu is open, or at the very least appear under the menu so it doesn't interfere with menu interaction. 

## Reproduction steps:

1. Go to /workspaces/directory, select a workspace with folders (e.g. Selenium Testing)
2. Click on the options menu next to a folder
3. Hover the mouse over items in the menu, in line with the folder items to the left
> The Options tooltip will appear
4. Try click on the menu items when the tooltip appears
> It won't work. 

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2259
