### ISSUE TITLE
[File View] Cursor doesn't change to pointer when hovering over "Download File" link

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#345]
## Description of the issue:

When hovering over the "Download File" link on the file view page, the cursor doesn't change to a pointer. It changes to the text 'I beam" cursor. 

## Expected behaviour:

When the cursor is over the "Download File" link it should switch to a pointer.

## Reproduction steps:

1. Find/add a folder containing a file (or upload one)
2. Go to the file view page
3. Hover over "Download file" 
> Cursor switches to the text cursor

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2260
