### ISSUE TITLE
[File view] When using the Tab key to navigate, "Download file" doesn't get focused on

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#346]
## Description of the issue:

On the File view page, the "Download file" link doesn't receive focus when using the Tab key to navigate the page.

## Expected behaviour:

The browser should focus on the "Download file" link when using the Tab key to navigate.

## Reproduction steps:

1. Find/add a folder containing a file (or upload one)
2. Open the file 
3. Use the Tab key to navigate the page
> Download file link doesn't receive focus

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2261
