### ISSUE TITLE
[Folder Navigation] Browsing 2 folders then going back results in 2 highlighted folders in navigation menu

### ISSUE THREAD

**Issue by declanslevin** [FutureNHS/futurenhs-platform#359]
## Description of the issue:

If you open a folder, then open a second before hitting the back button, you end up with both folders highlighted in the folder navigation menu.

## Screenshot(s):

<img width="313" alt="Screenshot 2020-10-12 at 16 41 14" src="https://user-images.githubusercontent.com/33623842/95765418-c0e26180-0ca9-11eb-86c0-217202cc0b01.png">

## Expected behaviour:

After hitting back, only the actively open folder should be highlighted in the navigation menu.

## Reproduction steps:

1. Open a folder
2. Open a second folder
3. Hit the back button
> Both folders will be highlighted

## Affected OS/Browsers:

Mac OS 10.15.2 Catalina / Chrome v85

**Comment by frigus02** [comment]
Tracked in https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2262
