### ISSUE TITLE
'Options' menu tooltip causes horizontal scrolling.

### ISSUE THREAD

**Issue by matt-paul** [FutureNHS/futurenhs-platform#419]
## Description of the issue:

On smaller devices (eg mobile), the 'options' menu tooltip causes horizontal scrolling.

## Screenshot(s):
File Page:
<img width="442" alt="Screenshot 2020-10-27 at 10 21 51" src="https://user-images.githubusercontent.com/13286587/97297254-a8e21480-1849-11eb-8fbb-0515b4ff7167.png">

If relevant please provide a screenshot of the issue.

## Expected behaviour:

There should not be scrolling

## Reproduction steps:

1) View as mobile
2) Go to file homepage
3) Click on 'file menu'
4) Note 'options tooltip is off screen and use can scroll to the right

## Affected OS/Browsers:

Firefox, presumably all browsers.

**Comment by frigus02** [comment]
Tracked in: https://dev.azure.com/futurenhs/FutureNHS/_workitems/edit/2313
